apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-multi-env-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: 'https://github.com/MyMirelHub/test'
        revision: HEAD
        directories:
          - path: k8s/overlays/Development
          - path: k8s/overlays/Staging
          - path: k8s/overlays/Production
  template:
    metadata:
      # Use environment-based names
      name: '{{path.basename}}-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/MyMirelHub/test'
        targetRevision: HEAD
        path: 'k8s/overlays/{{path.basename}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{path.basename}}'  # Hardcoded namespace based on environment
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 3