apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-dev

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: k8s-go-app
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/mymirelhub/test:latest
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: ENV
            value: "dev"