name: CI Build, Test and Push to GHCR and DockerHub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Run Go Tests
      run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: mirel1
        password: ${{ secrets.DOCKERHUB_PASSWORD }}  

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/mymirelhub/test:latest

    - name: Build and Push DockerHub Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: docker.io/mirel1/test:latest